In [1]:
import pandas as pd
import numpy as np

In [2]:
bycountry = pd.read_csv("Databycountry.csv")

In [3]:
bycountry.head()

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,...,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured
0,ABW,LCN,Aruba,HIC,35563.312500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,89.0,NaN,NaN
1,AFG,SAS,Afghanistan,LIC,2057.062256,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
2,AGO,SSF,Angola,LMC,8036.690430,51.8,6.7,4.4,11.50,11.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALB,ECS,Albania,UMC,13724.058594,51.4,4.5,4.8,15.21,9.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some disposal sites
4,AND,ECS,Andorra,HIC,43711.800781,31.2,8.2,2.6,11.60,35.1,...,NaN,52.1,NaN,NaN,NaN,NaN,NaN,47.9,NaN,NaN

In [6]:
bycountry

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,...,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured
0,ABW,LCN,Aruba,HIC,35563.312500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,89.0,NaN,NaN
1,AFG,SAS,Afghanistan,LIC,2057.062256,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
2,AGO,SSF,Angola,LMC,8036.690430,51.800000,6.700000,4.400000,11.500000,11.900000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALB,ECS,Albania,UMC,13724.058594,51.400000,4.500000,4.800000,15.210000,9.900000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some disposal sites
4,AND,ECS,Andorra,HIC,43711.800781,31.200000,8.200000,2.600000,11.600000,35.100000,...,NaN,52.1,NaN,NaN,NaN,NaN,NaN,47.9,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,XKX,ECS,Kosovo,LMC,9723.561523,42.000000,6.000000,6.000000,20.000000,8.000000,...,66.43,NaN,NaN,33.57,NaN,NaN,NaN,NaN,NaN,NaN
213,YEM,MEA,"Yemen, Rep.",LIC,8269.671875,65.000000,1.000000,6.000000,6.000000,7.000000,...,12.00,NaN,NaN,25.00,NaN,8.0,NaN,47.0,8.0,Other
214,ZAF,SSF,South Africa,UMC,12666.607422,16.381655,5.200216,16.910461,45.020646,9.396918,...,72.00,NaN,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN
215,ZMB,SSF,Zambia,LMC,3201.289307,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,ZWE,SSF,Zimbabwe,LIC,3190.506592,36.000000,5.000000,6.000000,3.000000,27.000000,...,NaN,NaN,NaN,NaN,NaN,16.0,NaN,84.0,NaN,NaN

In [19]:
#Drop the columns that are not necessary for the analysis

bycountry.drop (columns=['iso3c', 
                         'region_id', 
                         'other_information_information_system_for_solid_waste_management',
                         'other_information_national_agency_to_enforce_solid_waste_laws_and_regulations',
                         'other_information_national_law_governing_solid_waste_management_in_the_country', 
                         'other_information_ppp_rules_and_regulations',
                         'other_information_summary_of_key_solid_waste_information_made_available_to_the_public',
                         'special_waste_agricultural_waste_tons_year',
                         'special_waste_e_waste_tons_year',
                         'special_waste_hazardous_waste_tons_year',
                         'special_waste_industrial_waste_tons_year',
                         'special_waste_medical_waste_tons_year',
                         'waste_collection_coverage_rural_percent_of_geographic_area',
                         'waste_collection_coverage_rural_percent_of_households',
                         'waste_collection_coverage_rural_percent_of_population',
                         'waste_collection_coverage_rural_percent_of_waste',
                         'waste_collection_coverage_rural_percent_of_waste',
                         'waste_treatment_anaerobic_digestion_percent',
                         'waste_treatment_controlled_landfill_percent', 
                         'waste_treatment_incineration_percent',
                         'waste_treatment_landfill_unspecified_percent',
                         'waste_treatment_open_dump_percent', 
                         'waste_treatment_other_percent',
                         'waste_treatment_sanitary_landfill_landfill_gas_system_percent',
                         'waste_treatment_unaccounted_for_percent',
                         'waste_treatment_waterways_marine_percent',
                         'where_where_is_this_data_measured'],inplace=True)

In [20]:
bycountry.columns

Index(['country_name', 'income_id', 'gdp',
       'composition_food_organic_waste_percent', 'composition_glass_percent',
       'composition_metal_percent', 'composition_other_percent',
       'composition_paper_cardboard_percent', 'composition_plastic_percent',
       'composition_rubber_leather_percent', 'composition_wood_percent',
       'composition_yard_garden_green_waste_percent',
       'population_population_number_of_people',
       'special_waste_construction_and_demolition_waste_tons_year',
       'total_msw_total_msw_generated_tons_year',
       'waste_collection_coverage_total_percent_of_geographic_area',
       'waste_collection_coverage_total_percent_of_households',
       'waste_collection_coverage_total_percent_of_population',
       'waste_collection_coverage_total_percent_of_waste',
       'waste_collection_coverage_urban_percent_of_geographic_area',
       'waste_collection_coverage_urban_percent_of_households',
       'waste_collection_coverage_urban_percent_of_population',
       'waste_collection_coverage_urban_percent_of_waste',
       'waste_treatment_compost_percent', 'waste_treatment_recycling_percent'],
      dtype='object')

In [23]:
#rename names of columns for better understanding


bycountry.rename(columns={'composition_food_organic_waste_percent': 'organic_food_percent', 
                           'composition_glass_percent': 'glass_percent', 
                           'composition_metal_percent': 'metal_percent',
                           'composition_other_percent': 'other_waste_percent',
                           'composition_paper_cardboard_percent': 'paper_cardboard_percent',
                           'composition_plastic_percent':'plastic_percent',
                           'composition_rubber_leather_percent': 'rubber_leather_percent',
                           'composition_wood_percent':'wood_percent',
                           'composition_yard_garden_green_waste_percent':'yard_garden_green_waste_percent',
                           'population_population_number_of_people': 'population_number_of_people',
                           'waste_collection_coverage_total_percent_of_geographic_area':'waste_collected_total_percent_geographic_area',
                           'waste_collection_coverage_urban_percent_of_households':'waste_collected_total_percent_of_households',
                           'waste_collection_coverage_total_percent_of_population': 'waste_collected_total_percent_of_popuation',
                           'waste_collection_coverage_urban_percent_of_waste': 'waste_collected_urban_percent_of_waste'} , inplace=True)

In [30]:
bycountry.head()

,country_name,gdp,organic_food_percent,glass_percent,metal_percent,other_waste_percent,paper_cardboard_percent,plastic_percent,rubber_leather_percent,wood_percent,...,waste_collected_total_percent_geographic_area,waste_collection_coverage_total_percent_of_households,waste_collected_total_percent_of_popuation,waste_collection_coverage_total_percent_of_waste,waste_collection_coverage_urban_percent_of_geographic_area,waste_collected_total_percent_of_households,waste_collection_coverage_urban_percent_of_population,waste_collected_urban_percent_of_waste,waste_treatment_compost_percent,waste_treatment_recycling_percent
0,Aruba,35563.312500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0
1,Afghanistan,2057.062256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,8036.690430,51.8,6.7,4.4,11.50,11.9,13.5,NaN,NaN,...,NaN,NaN,23.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Albania,13724.058594,51.4,4.5,4.8,15.21,9.9,9.6,NaN,4.6,...,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,43711.800781,31.2,8.2,2.6,11.60,35.1,11.3,NaN,NaN,...,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
bycountry.isna()

,country_name,income_id,gdp,organic_food_percent,glass_percent,metal_percent,other_waste_percent,paper_cardboard_percent,plastic_percent,rubber_leather_percent,...,waste_collected_total_percent_geographic_area,waste_collection_coverage_total_percent_of_households,waste_collected_total_percent_of_popuation,waste_collection_coverage_total_percent_of_waste,waste_collection_coverage_urban_percent_of_geographic_area,waste_collected_total_percent_of_households,waste_collection_coverage_urban_percent_of_population,waste_collected_urban_percent_of_waste,waste_treatment_compost_percent,waste_treatment_recycling_percent
0,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
1,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,True,...,True,True,False,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,True,...,True,True,False,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,True,...,True,True,False,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,False,False,False,False,False,False,False,False,False,True,...,True,True,False,True,True,True,False,True,True,True
213,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,True,True,True,True,True,False
214,False,False,False,False,False,False,False,False,False,True,...,True,False,True,True,True,False,True,True,True,False
215,False,False,False,True,True,True,True,True,True,True,...,True,False,False,True,True,True,True,True,True,True
216,False,False,False,False,False,False,False,False,False,True,...,True,False,True,True,True,True,True,True,True,False

Empty DataFrame
Columns: [country_name, income_id, gdp, organic_food_percent, glass_percent, metal_percent, other_waste_percent, paper_cardboard_percent, plastic_percent, rubber_leather_percent, wood_percent, yard_garden_green_waste_percent, population_number_of_people, special_waste_construction_and_demolition_waste_tons_year, total_msw_total_msw_generated_tons_year, waste_collected_total_percent_geographic_area, waste_collection_coverage_total_percent_of_households, waste_collected_total_percent_of_popuation, waste_collection_coverage_total_percent_of_waste, waste_collection_coverage_urban_percent_of_geographic_area, waste_collected_total_percent_of_households, waste_collection_coverage_urban_percent_of_population, waste_collected_urban_percent_of_waste, waste_treatment_compost_percent, waste_treatment_recycling_percent]
Index: []

[0 rows x 25 columns]

In [29]:
#drop another column that I found is not necessary for the analysis

bycountry.drop (columns=['income_id'], inplace=True)

,country_name,gdp,organic_food_percent,glass_percent,metal_percent,other_waste_percent,paper_cardboard_percent,plastic_percent,rubber_leather_percent,wood_percent,...,waste_collected_total_percent_geographic_area,waste_collection_coverage_total_percent_of_households,waste_collected_total_percent_of_popuation,waste_collection_coverage_total_percent_of_waste,waste_collection_coverage_urban_percent_of_geographic_area,waste_collected_total_percent_of_households,waste_collection_coverage_urban_percent_of_population,waste_collected_urban_percent_of_waste,waste_treatment_compost_percent,waste_treatment_recycling_percent
0,False,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
1,False,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,True,True,...,True,True,False,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,True,False,...,True,True,False,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,True,True,...,True,True,False,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,False,False,False,False,False,False,False,False,True,False,...,True,True,False,True,True,True,False,True,True,True
213,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,True,True,True,True,True,False
214,False,False,False,False,False,False,False,False,True,True,...,True,False,True,True,True,False,True,True,True,False
215,False,False,True,True,True,True,True,True,True,True,...,True,False,False,True,True,True,True,True,True,True
216,False,False,False,False,False,False,False,False,True,True,...,True,False,True,True,True,True,True,True,True,False

In [55]:
#create a new list to apply later in dropna to see if there is any country that has all the columns with missing values

new_list= list (bycountry.columns)

print(len(new_list))

new_list.remove('gdp')

new_list.remove('population_number_of_people')

new_list.remove('country_name')


print(new_list)

print(len(new_list))

24
['organic_food_percent', 'glass_percent', 'metal_percent', 'other_waste_percent', 'paper_cardboard_percent', 'plastic_percent', 'rubber_leather_percent', 'wood_percent', 'yard_garden_green_waste_percent', 'special_waste_construction_and_demolition_waste_tons_year', 'total_msw_total_msw_generated_tons_year', 'waste_collected_total_percent_geographic_area', 'waste_collection_coverage_total_percent_of_households', 'waste_collected_total_percent_of_popuation', 'waste_collection_coverage_total_percent_of_waste', 'waste_collection_coverage_urban_percent_of_geographic_area', 'waste_collected_total_percent_of_households', 'waste_collection_coverage_urban_percent_of_population', 'waste_collected_urban_percent_of_waste', 'waste_treatment_compost_percent', 'waste_treatment_recycling_percent']
21

In [56]:
#applied dropna but no rows were droped
bycountry.dropna (subset = new_list, how = 'all', inplace=True)

In [57]:
bycountry

,country_name,gdp,organic_food_percent,glass_percent,metal_percent,other_waste_percent,paper_cardboard_percent,plastic_percent,rubber_leather_percent,wood_percent,...,waste_collected_total_percent_geographic_area,waste_collection_coverage_total_percent_of_households,waste_collected_total_percent_of_popuation,waste_collection_coverage_total_percent_of_waste,waste_collection_coverage_urban_percent_of_geographic_area,waste_collected_total_percent_of_households,waste_collection_coverage_urban_percent_of_population,waste_collected_urban_percent_of_waste,waste_treatment_compost_percent,waste_treatment_recycling_percent
0,Aruba,35563.312500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0
1,Afghanistan,2057.062256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,8036.690430,51.800000,6.700000,4.400000,11.500000,11.900000,13.500000,NaN,NaN,...,NaN,NaN,23.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Albania,13724.058594,51.400000,4.500000,4.800000,15.210000,9.900000,9.600000,NaN,4.6,...,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,43711.800781,31.200000,8.200000,2.600000,11.600000,35.100000,11.300000,NaN,NaN,...,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,Kosovo,9723.561523,42.000000,6.000000,6.000000,20.000000,8.000000,11.000000,NaN,7.0,...,NaN,NaN,39.0,NaN,NaN,NaN,100.0,NaN,NaN,NaN
213,"Yemen, Rep.",8269.671875,65.000000,1.000000,6.000000,6.000000,7.000000,10.000000,1.0,3.0,...,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0
214,South Africa,12666.607422,16.381655,5.200216,16.910461,45.020646,9.396918,7.090104,NaN,NaN,...,NaN,64.0,NaN,NaN,NaN,90.5,NaN,NaN,NaN,28.0
215,Zambia,3201.289307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,Zimbabwe,3190.506592,36.000000,5.000000,6.000000,3.000000,27.000000,23.000000,NaN,NaN,...,NaN,63.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0

In [67]:
#creating a new column to count all the NanN values in this.
bycountry["#ofNAN"]=bycountry.isnull().sum(axis=1)

In [82]:
#sorting the values to see the how many missing values has each country

bycountry.sort_values('#ofNAN', ascending= False)

,country_name,gdp,organic_food_percent,glass_percent,metal_percent,other_waste_percent,paper_cardboard_percent,plastic_percent,rubber_leather_percent,wood_percent,yard_garden_green_waste_percent,population_number_of_people,special_waste_construction_and_demolition_waste_tons_year,total_msw_total_msw_generated_tons_year,waste_collected_total_percent_geographic_area,waste_collection_coverage_total_percent_of_households,waste_collected_total_percent_of_popuation,waste_collection_coverage_total_percent_of_waste,waste_collection_coverage_urban_percent_of_geographic_area,waste_collected_total_percent_of_households,waste_collection_coverage_urban_percent_of_population,waste_collected_urban_percent_of_waste,waste_treatment_compost_percent,waste_treatment_recycling_percent,#ofNAN
31,Central African Republic,822.610474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4515392,NaN,1.105983e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
176,South Sudan,1795.991943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11177490,NaN,2.680681e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
165,Rwanda,1950.528076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11917508,NaN,4.384969e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
51,Djibouti,6596.775391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,746221,NaN,1.149972e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
174,Somalia,1862.614136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14317996,NaN,2.326099e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,Pakistan,4571.414551,30.00,6.00,4.00,20.00,13.00,9.00,2.00,2.00,14.00,193203472,NaN,3.076000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,2.00,8.00,8
91,"Iran, Islamic Rep.",14535.862305,72.90,1.90,2.30,5.00,7.30,8.50,1.10,1.30,NaN,80277424,80000000.0,1.788500e+07,NaN,NaN,100.0,NaN,NaN,NaN,100.0,NaN,12.00,5.00,7
53,Denmark,57821.199219,12.78,5.78,6.29,23.86,11.57,1.61,0.00,7.65,30.46,5818553,11402900.0,4.910858e+06,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,18.99,27.27,7
18,Bulgaria,22279.361328,24.35,5.83,1.98,17.93,14.18,12.15,1.96,2.48,19.18,7025037,172369117.0,2.859190e+06,NaN,NaN,NaN,98.30,NaN,NaN,NaN,NaN,10.32,19.03,7
127,"Macedonia, FYR",16147.729492,29.30,4.10,2.50,19.80,12.80,13.90,0.90,0.70,16.00,2082958,121551.0,6.269704e+05,NaN,NaN,73.0,76.61,NaN,NaN,NaN,NaN,0.10,0.18,6

In [80]:
pd.set_option('display.max_columns', None)

In [81]:
bycountry

,country_name,gdp,organic_food_percent,glass_percent,metal_percent,other_waste_percent,paper_cardboard_percent,plastic_percent,rubber_leather_percent,wood_percent,yard_garden_green_waste_percent,population_number_of_people,special_waste_construction_and_demolition_waste_tons_year,total_msw_total_msw_generated_tons_year,waste_collected_total_percent_geographic_area,waste_collection_coverage_total_percent_of_households,waste_collected_total_percent_of_popuation,waste_collection_coverage_total_percent_of_waste,waste_collection_coverage_urban_percent_of_geographic_area,waste_collected_total_percent_of_households,waste_collection_coverage_urban_percent_of_population,waste_collected_urban_percent_of_waste,waste_treatment_compost_percent,waste_treatment_recycling_percent,#ofNAN
0,Aruba,35563.312500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103187,NaN,8.813202e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,19
1,Afghanistan,2057.062256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34656032,NaN,5.628525e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
2,Angola,8036.690430,51.800000,6.700000,4.400000,11.500000,11.900000,13.500000,NaN,NaN,NaN,25096150,NaN,4.213644e+06,NaN,NaN,23.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
3,Albania,13724.058594,51.400000,4.500000,4.800000,15.210000,9.900000,9.600000,NaN,4.6,NaN,2854191,203009.0,1.087447e+06,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
4,Andorra,43711.800781,31.200000,8.200000,2.600000,11.600000,35.100000,11.300000,NaN,NaN,NaN,82431,NaN,4.300000e+04,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,Kosovo,9723.561523,42.000000,6.000000,6.000000,20.000000,8.000000,11.000000,NaN,7.0,NaN,1801800,217241.0,3.190000e+05,NaN,NaN,39.0,NaN,NaN,NaN,100.0,NaN,NaN,NaN,10
213,"Yemen, Rep.",8269.671875,65.000000,1.000000,6.000000,6.000000,7.000000,10.000000,1.0,3.0,1.0,27584212,NaN,4.836820e+06,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,9
214,South Africa,12666.607422,16.381655,5.200216,16.910461,45.020646,9.396918,7.090104,NaN,NaN,NaN,51729344,NaN,1.845723e+07,NaN,64.0,NaN,NaN,NaN,90.5,NaN,NaN,NaN,28.0,11
215,Zambia,3201.289307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14264756,NaN,2.608268e+06,NaN,10.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
216,Zimbabwe,3190.506592,36.000000,5.000000,6.000000,3.000000,27.000000,23.000000,NaN,NaN,NaN,12500525,NaN,1.449752e+06,NaN,63.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,12